package com.ak.redrob.model;

import lombok.Builder;

import java.io.Serial;
import java.io.Serializable;
import java.util.Map;

/**
 * Represents a ranked candidate after evaluation.
 *
 * <p>This object is generated by the scoring engine and is passed
 * to the ranking engine for Top-K selection.</p>
 *
 * @param candidate Original candidate
 * @param totalScore Final weighted score (0-100)
 * @param componentScores Individual component scores
 * @param reasoning Human-readable explanation for the score
 */
@Builder
public record ScoredCandidate(

        Candidate candidate,

        double totalScore,

        Map<String, Double> componentScores,

        String reasoning

) implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

}